version: '2'

services:
    login:
        container_name: login
        build:
            context: ./admin
        ports:
            - "5001:5001"
        volumes:
            - ./admin:/code
        # depends_on:
        #     - shortener
        
    shortener:
        container_name: shortener
        build:
            context: ./frontend
        ports:
            - "5000:5000"
        volumes:
            - ./frontend:/code
        depends_on:
            - login
